[package]
name = "bestme-tauri"
version = "0.1.0"
description = "BestMe Tauri Application"
authors = ["BestMe Team"]
edition = "2021"
rust-version = "1.75"

[build-dependencies]
tauri-build = { version = "2.0.3", features = [] }

[dependencies]
serde_json = "1.0.135"
serde = { version = "1.0.217", features = ["derive"] }
log = "0.4.22"
anyhow = "1.0.94"
parking_lot = "0.12.3"
bestme = { path = "..", features = ["config", "text-injection", "storage", "audio", "transcribe", "commands", "ai-local"] }
reqwest = { version = "0.12.12", features = ["json", "stream"] }
tokio-util = { version = "0.7.13", features = ["codec"] }
tokio-stream = "0.1.16"
futures = "0.3.31"
tokio = { version = "1.42.0", features = ["full"] }
env_logger = "0.11.5"
regex = "1.11.1"
chrono = { version = "0.4.39", features = ["serde"] }
dirs = "5.0"
# whisper-rs = "0.11.1"
uuid = { version = "1.11.0", features = ["v4", "serde"] }

# Tauri dependency
tauri = { version = "2.1.1", features = ["tray-icon"] }

# Added for system monitoring
sysinfo = "0.33.0"
once_cell = "1.20.2"

# Fix for dependency issues  
secret-service = { version = "4", features = ["rt-tokio-crypto-rust"] }

# AI telemetry dependencies
opentelemetry = { version = "0.24", features = ["metrics", "trace"] }

# Audio dependencies
cpal = "0.15.3"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

# default = ["audio-plugin", "transcribe-plugin", "voice-command-plugin"]

audio-plugin = []
transcribe-plugin = []
voice-command-plugin = []

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true 
